[project]
name = "mycosmo"
version = "0.1.0"
description = "This is an example cosmology package."
readme = "README.md"
authors = [
    { name = "sfarrens", email = "samuel.farrens@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
lint = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "ruff>=0.16.3",
]
test = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-emoji>=0.2.0",
]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
addopts = ["--verbose", "--emoji", "--cov=mycosmo"]
testpaths = ["tests"]
